name: Build

on:
  push:
    branches: [ main ]
    paths:
    - 'README.md'
    - 'screenshot.png'
    - 'widget.json'
    - 'icinga.py'
    - 'icinga.coffee'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip files
        run: zip icinga.widget.zip widget.json screenshot.png README.md LICENSE icinga.coffee icinga.p

      - name: Add and push zip file
        run: |
          git config --global user.email "gicara+uebersicht@gmail.com"
          git config --global user.name "G. Carafa"
          git add icinga.widget.zip
          git commit -m "added rebuilded zip file"
          git push